.TH "transfer" "1" "December 2017" "1.0.0" ""

.SH "NAME"
\fBtransfer\fR - Learn HTTP interactively

.SH "DESCRIPTION"
.P
\fBtransfer\fR(1) is an interactive tutorial that learns you HTTP.

It runs in Node and is installed with npm.
You\(cqre expected to talk to it with Curl.

It mocks a movie API, but you discover that while walking through the tutorial
and interacting with it over HTTP.

.SH "BUGS"
.P
<\fIhttps://github.com/cmda-be/transfer/issues\fR>

.SH "AUTHOR"
.P
Written by Titus Wormer <\fItituswormer@gmail.com\fR>

.SH "LICENSE"
.P
MIT \(co Titus Wormer
